name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
template: |
  ## What's Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
