name: Publish Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/test-chart/Chart.yaml'
      - 'charts/test-chart/values.yaml'
      - 'charts/test-chart/templates/**'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: MaterializeInc/chart-releaser-action@add-flag-to-skip-tag-and-release
        with:
          skip_release: true
          packages_with_index: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
