name: Publish Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/test-chart/**'

permissions:
  contents: write
  pull-requests: write  # Added for PR creation

env:
  CHART_DIR: charts/test-chart
  GITHUB_PAGES_BRANCH: gh-pages
  RELEASE_DIR: .cr-release-packages

jobs:
  publish:
    name: Package and Publish
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: latest

      - name: Extract chart version
        id: chart-version
        run: |
          VERSION=$(yq eval '.version' ${CHART_DIR}/Chart.yaml)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Chart version: ${VERSION}"

      - name: Lint Helm chart
        run: |
          helm lint ${CHART_DIR}

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_PAGES_BRANCH }}
          path: gh-pages
          clean: true

      - name: Check existing version
        id: version-check
        run: |
          if [ -f "gh-pages/${CHART_DIR##*/}-${{ steps.chart-version.outputs.version }}.tgz" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Chart version ${{ steps.chart-version.outputs.version }} already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Chart version ${{ steps.chart-version.outputs.version }} is new"
          fi

      - name: Package chart
        if: steps.version-check.outputs.exists == 'false'
        run: |
          mkdir -p ${RELEASE_DIR}
          helm package ${CHART_DIR} --destination ${RELEASE_DIR}
          cp ${RELEASE_DIR}/*.tgz gh-pages/

          cd gh-pages
          REPO_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          if [ -f index.yaml ]; then
            helm repo index . --url "${REPO_URL}" --merge index.yaml
          else
            helm repo index . --url "${REPO_URL}"
          fi

      - name: Create Pull Request
        if: steps.version-check.outputs.exists == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: helm-release-${{ steps.chart-version.outputs.version }}
          delete-branch: true
          base: ${{ env.GITHUB_PAGES_BRANCH }}
          title: "helm-chart: publish helm chart ${{ steps.chart-version.outputs.version }}"
          commit-message: "helm-chart: publish helm chart version ${{ steps.chart-version.outputs.version }}"
          body: |
            Automated PR to publish new Helm chart version ${{ steps.chart-version.outputs.version }}

            Changes:
            - Added new chart package
            - Updated Helm repository index

            This PR was automatically created by the Helm chart publishing workflow.
          labels: |
            helm-release
            automated-pr
