# Helm Chart Publishing Workflow
# - Packages charts and pushes to the gh-pages branch
# - Updates Helm repository index

name: Publish Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/test-chart/Chart.yaml'
      - 'charts/test-chart/values.yaml'
      - 'charts/test-chart/templates/**'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: misc/helm-charts/operator
          packages_with_index: true
          skip_upload: true
          pages_branch: gh-pages
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
